## Numbers Dates and Timezones

In [1]:
# Round float number to a fixed number of decimal places:


round(1.2352342342, 2)

1.24

In [3]:
# Round could also be used on int units:
round(23, -1)

20

In [6]:
# Python float operations often lead into small mathematical errors:
2.1 + 4.2

6.300000000000001

In [8]:
# If we want to avoid this, we can use de decimal library:
from decimal import Decimal
Decimal('2.1') + Decimal('4.2')

Decimal('6.3')

In [11]:
Decimal('6.3').__float__()

6.3

In [ ]:
# By the way, is is much more common using float type instead of decimal library,
# mainly because it is faster and also de preccision is enough

In [14]:
# The formatting functionality has already been described in the last chapter (2)
# In order to use exponential notation:

f"{23.23412341234:.2e}"

'2.32e+01'

In [23]:
# Converting integers to byte notation and viceersa: use int.to_bytes and int.from_bytes:
data = b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'
int.from_bytes(data, 'little')

69120565665751139577663547927094891008

In [31]:
int.to_bytes(69120565665751139577663547927094891008,16, 'little')

b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'

In [32]:
# Complex number: 2 ways of writing: 
a = complex(2,4)  # 1pos: real, 2pos: imaginary
b = 3-5j
c = a + b 
c

(5-1j)

In [33]:
c.real, c.imag

(5.0, -1.0)

In [35]:
# Conjugate:
c.conjugate()

(5+1j)

In [36]:
# In order to get a complex number as a result of an operation, the cmath is needed:
import math, cmath

In [37]:
math.sqrt(-1)

ValueError: math domain error

In [38]:
cmath.sqrt(-1)

1j

In [39]:
# Infinite and Null values
a = float('inf')
b = float('-inf')
c = float('nan')

In [40]:
# Checking types
math.isinf(a), math.isnan(c)

(True, True)

In [42]:
# Vectorized operations: avoid using lists:
example_list = [1,2,3,4]
mult_result = example_list * 2
sum_result = example_list + example_list

In [43]:
mult_result, sum_result

([1, 2, 3, 4, 1, 2, 3, 4], [1, 2, 3, 4, 1, 2, 3, 4])

In [47]:
# Use numpy library for these types of problmes
import numpy as np
np.array(example_list)*2

array([2, 4, 6, 8])

In [55]:
# Creating matrix
a = np.array([[1, 2, 3], [5, 6, 7], [9, 10, 11]])
a

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [56]:
# Conditional assingmnet on a matrix:
np.where(a>10, a, 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 11]])

In [59]:
# Random:
import random
values = [1,2,3,4,5,6]

# Specify seed in order to obtain reproducible results
random.seed(42)

In [60]:
random.choice(values)

6

In [61]:
# Get two numbers without replacement
random.sample(values, 2)

[1, 6]

In [63]:
# Get two numbers with replacement
random.choices(values, k = 2)

[5, 2]

In [65]:
# Integer inside and interval:
random.randint(0, 10)

2

In [66]:
# Float between interval with uniform prob distribution
random.uniform(0,20)

14.729424283280249

In [67]:
# Dates
from datetime import datetime, timedelta
a = datetime(2021, 11, 28)

In [68]:
a

datetime.datetime(2021, 11, 28, 0, 0)

In [69]:
a.strftime('%Y-%m-%d')

'2021-11-28'

In [72]:
# Add or substract time
(a + timedelta(days = 3)).strftime('%Y-%m-%d')

'2021-12-01'

In [73]:
# Get datetime atm
datetime.today()

datetime.datetime(2021, 11, 7, 13, 1, 0, 728498)

In [75]:
# Same result
datetime.now()

datetime.datetime(2021, 11, 7, 13, 1, 47, 639985)

In [92]:
# Finding a date for the last occurrence of a day of the week
weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

def get_current_weeks_x_date(day)-> datetime:
    today = datetime.now()
    todays_weekday = today.weekday()
    difference = weekdays.index(day) - todays_weekday
    result_date = today + timedelta(days = difference)
    return result_date.strftime('%Y-%m-%d')

In [94]:
get_current_weeks_x_date('Friday')

'2021-11-05'

In [95]:
# Getting current month daterange: use calendar and monthrange and datetime.replace
import calendar

In [102]:
print(calendar.month(theyear=2021, themonth=11))

   November 2021
Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7
 8  9 10 11 12 13 14
15 16 17 18 19 20 21
22 23 24 25 26 27 28
29 30



In [107]:
first_day, last_day = calendar.monthrange(2021, 11)

In [110]:
month_date_range = [datetime(2021, 11, day) for day in range(first_day +1,last_day+1)]
for date in month_date_range:
    print(date)

2021-11-01 00:00:00
2021-11-02 00:00:00
2021-11-03 00:00:00
2021-11-04 00:00:00
2021-11-05 00:00:00
2021-11-06 00:00:00
2021-11-07 00:00:00
2021-11-08 00:00:00
2021-11-09 00:00:00
2021-11-10 00:00:00
2021-11-11 00:00:00
2021-11-12 00:00:00
2021-11-13 00:00:00
2021-11-14 00:00:00
2021-11-15 00:00:00
2021-11-16 00:00:00
2021-11-17 00:00:00
2021-11-18 00:00:00
2021-11-19 00:00:00
2021-11-20 00:00:00
2021-11-21 00:00:00
2021-11-22 00:00:00
2021-11-23 00:00:00
2021-11-24 00:00:00
2021-11-25 00:00:00
2021-11-26 00:00:00
2021-11-27 00:00:00
2021-11-28 00:00:00
2021-11-29 00:00:00
2021-11-30 00:00:00


In [120]:
# Dates and timezones
from pytz import timezone

timezone_in_Madrid = timezone('Europe/Madrid')
time_in_madrid = timezone_in_Madrid.localize(datetime.now())
time_in_madrid

datetime.datetime(2021, 11, 7, 14, 5, 14, 181023, tzinfo=<DstTzInfo 'Europe/Madrid' CET+1:00:00 STD>)

In [121]:
# If wanna see the time in London
time_in_madrid.astimezone(timezone('Europe/London'))

datetime.datetime(2021, 11, 7, 13, 5, 14, 181023, tzinfo=<DstTzInfo 'Europe/London' GMT0:00:00 STD>)

In [125]:
# It is highly reccommended to use utc as timezone, once all the arithmetics
# have been done, translate it to local timezone:

utc_time_zone = timezone('utc').localize(datetime.now())
utc_time_zone_next_week = utc_time_zone + timedelta(days = 7)
utc_time_zone_next_week_madrid = utc_time_zone_next_week.astimezone(timezone('Europe/Madrid'))

In [126]:
utc_time_zone_next_week_madrid

datetime.datetime(2021, 11, 14, 15, 11, 46, 44853, tzinfo=<DstTzInfo 'Europe/Madrid' CET+1:00:00 STD>)